"""initial creation

Revision ID: cf4fd3a827d7
Revises: 
Create Date: 2019-03-31 10:38:56.374592

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf4fd3a827d7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('about_me', sa.String(length=140), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    op.create_table('problem',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('color', sa.String(length=32), nullable=True),
    sa.Column('grade', sa.String(length=3), nullable=True),
    sa.Column('risk', sa.Integer(), nullable=True),
    sa.Column('intensity', sa.Integer(), nullable=True),
    sa.Column('complexity', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_problem_color'), 'problem', ['color'], unique=False)
    op.create_index(op.f('ix_problem_complexity'), 'problem', ['complexity'], unique=False)
    op.create_index(op.f('ix_problem_grade'), 'problem', ['grade'], unique=False)
    op.create_index(op.f('ix_problem_intensity'), 'problem', ['intensity'], unique=False)
    op.create_index(op.f('ix_problem_risk'), 'problem', ['risk'], unique=False)
    op.create_index(op.f('ix_problem_timestamp'), 'problem', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_problem_timestamp'), table_name='problem')
    op.drop_index(op.f('ix_problem_risk'), table_name='problem')
    op.drop_index(op.f('ix_problem_intensity'), table_name='problem')
    op.drop_index(op.f('ix_problem_grade'), table_name='problem')
    op.drop_index(op.f('ix_problem_complexity'), table_name='problem')
    op.drop_index(op.f('ix_problem_color'), table_name='problem')
    op.drop_table('problem')
    op.drop_table('followers')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
